#!/usr/bin/env bash
# Nginx running, and listening on port 80 of all the server’s active IPv4 IPs 

cp -r /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
